#!/bin/env bash

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#f58814E6'
TEXT='#ffffffE6'
WRONG='#880000bb'
VERIFYING='#15b304E6'
CORRECT='#9906c2bb'

i3lock \
    --insidever-color=$CLEAR \
    --ringver-color=$VERIFYING \
    \
    --insidewrong-color=$CLEAR \
    --ringwrong-color=$WRONG \
    \
    --inside-color=$BLANK \
    --ring-color=$DEFAULT \
    --line-color=$BLANK \
    --separator-color=$DEFAULT \
    \
    --verif-color=$TEXT \
    --wrong-color=$TEXT \
    --time-color=$TEXT \
    --date-color=$TEXT \
    --keyhl-color=$CORRECT \
    --bshl-color=$WRONG \
    \
    --screen 1 \
    --blur 9 \
    --clock \
    --indicator \
    --time-str="%H:%M:%S" \
    --date-str="%A, %Y-%m-%d" \
