term-osd-bar=yes # displays a progress bar on the terminal

# Sets volume to 80%.
volume=100

# set max volume
volume-max=120

# Normalizes audio
af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5'

# bolden subtitles
sub-bold=yes

# hardware acceleration
hwdec=auto

# save last position
# save-position-on-quit

# set youtube video resolution
ytdl-format="bestvideo[height<=?1080]+bestaudio/best"
