# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
  colors = true
  interval = 1
}

order += "volume master"
order += "wireless _first_"
order += "battery 1"
order += "cpu_temperature 0"
order += "memory"
order += "tztime local"


volume master {
  device = "default"
}

wireless _first_ {
  format_up = "\uf1eb%quality %essid"
  format_down = "Disconnected"
}

battery 1 {
  format = "%status %percentage"
  format_down = "No battery"
	format_percentage = "%.f%s"
  status_chr = "\u26a1"
  status_bat = "\U0001f50b"
  status_unk = "? UNK"
  status_full = "\u263b FULL"
  path = "/sys/class/power_supply/BAT%d/uevent"
  low_threshold = 15
}

cpu_temperature 0 {
  format = "\uf2c9 %degrees °C"
	max_threshold = 75
	path = "/sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input"
}

memory {
  format = "\uf2db %used"
  threshold_degraded = "15%"
	threshold_critical = "5%"
	format_degraded = "\uf2db %free"
}

tztime local {
  format = "%a, %b %e | %H:%M:%S "
}
